# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 14:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('sv', 'Saving'), ('cr', 'Current')], default='sv', max_length=10)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.EmailField(max_length=254, unique=True)),
                ('aadhar_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('salary', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='EmpAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.EmailField(max_length=254, unique=True)),
                ('access_key', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.EmailField(blank=True, default='default', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('salary', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('end_time', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)])),
                ('amount_left', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('monthly_due_date', models.DateTimeField()),
                ('amount_taken', models.IntegerField(default=0)),
                ('last_payment_date', models.DateTimeField(default=datetime.datetime(2017, 10, 19, 14, 12, 28, 983066))),
                ('interest_rate', models.FloatField(default=0.15)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='system.Account')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_prof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='system.Customer'),
        ),
    ]
