# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 09:46
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar_id',
            field=models.IntegerField(max_length=11, validators=[django.core.validators.RegexValidator('\\d{11,11}', 'Number must be 11 digits', 'Invalid number')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='last_payment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 9, 9, 13, 752525)),
        ),
    ]
